server:
  port: 8003
spring:
  application:
    name: cloud-eureka-consumer
eureka:
  instance:
    hostname: eureka-consumer8003.com
  client:
    service-url:
      defaultZone: http://eureka-server7001.com:7001/eureka/,http://eureka-server7002.com:7002/eureka/