server:
  port: 8005
spring:
  application:
    name: cloud-openfeign-consumer
eureka:
  instance:
    hostname: openfeign-consumer8005.com
  client:
    service-url:
      defaultZone: http://eureka-server7001.com:7001/eureka/,http://eureka-server7002.com:7002/eureka/